= Тестовое задание s7

== Суть задания

- Необходимо разработать сервис, для разбора входящего csv файла в директорию и базу данных.

=== Требования
- Каждые 2 минуты (+- 30сек) в папку 'In' файловой системы поступает файл в формате csv, все поля обязательные имя файла в
формате '20221129_1234_DME.csv' - '<год><месяц><день>_<номер рейса>_<аэропорт вылета>.csv'
- При появлении файла (Приложение 1) в папке нужно преобразовать файл в формат json (Приложение 2) и сохранить его в
папке 'Out'. Исходный файл переместить в папку 'Ok'. В случае возникновения ошибок файл переместить в папку 'Err'.
Успешно обработанные файлы поместить в таблицу 'flight'(Приложение 3) базы данных SQLite (или другую на выбор).

=== Дополнительные требования
- Процессы сохранения файла в папку и в БД желательно сделать параллельными.
- Базу данных и таблицу flight создать при первом запуске программы
- Все действия сервиса должны выводиться в лог
- Реализовать REST API метод для выборки всех рейсов из таблицы flight за определённую дату